// VERSION: v4.8 - INPUT_PULLUP fix for reliable MIC detection (2026-08-24)
#include <avr/sleep.h>
#include <avr/interrupt.h>

// --- HARDWARE PINS ---
#define MIC_OUT_PIN  0  // PB0: Sends wake pulse to ESP32 Pin 4
#define PIR_IN_PIN   1  // PB1: PCINT1 (From PIR module)
#define PIR_OUT_PIN  2  // PB2: Sends wake pulse to ESP32 Pin 13
#define MIC_IN_PIN   4  // PB4: PCINT4 (From 4-Pin Mic DO pin)
bool lastPirState = LOW;
bool lastMicState = LOW; // Explicit state tracking for the Mic

// Interrupt Service Routine (ISR)
ISR(PCINT0_vect) {
  // MCU wakes up. Hardware automatically clears the interrupt flag here.
}

void setup() {
  pinMode(PIR_OUT_PIN, OUTPUT);
  pinMode(MIC_OUT_PIN, OUTPUT);
  
  digitalWrite(PIR_OUT_PIN, LOW);
  digitalWrite(MIC_OUT_PIN, LOW);

  pinMode(PIR_IN_PIN, INPUT);
  pinMode(MIC_IN_PIN, INPUT_PULLUP); // Internal pull-up to 5V ensures clean idle HIGH.
                                       // LM393 open-collector pulls LOW on sound.
                                       // Works for ANY MIC polarity — no circuit changes needed.

  // Configure Pin Change Interrupts
  GIMSK |= (1 << PCIE);    
  PCMSK |= (1 << PCINT1);  
  PCMSK |= (1 << PCINT4);  

  set_sleep_mode(SLEEP_MODE_PWR_DOWN);
}

void loop() {
  // Read BOTH sensors immediately upon waking
  bool currentPirState = digitalRead(PIR_IN_PIN);
  bool currentMicState = digitalRead(MIC_IN_PIN);

  // --- 1. PIR LOGIC ---
  if (currentPirState == HIGH && lastPirState == LOW) {
    digitalWrite(PIR_OUT_PIN, HIGH);
    delay(50); 
    digitalWrite(PIR_OUT_PIN, LOW);
  } 
  
  // --- 2. MIC LOGIC ---
  // Trigger on ANY state change (supports Active-HIGH and Active-LOW sound modules!)
  if (currentMicState != lastMicState) {
    digitalWrite(MIC_OUT_PIN, HIGH);
    delay(50);
    digitalWrite(MIC_OUT_PIN, LOW);
    
    // 500ms acoustic debounce to outlast echoing
    delay(500); 
  }

  // Update trackers for the next wake cycle
  lastPirState = currentPirState;
  
  // Re-read the mic state after the 500ms debounce delay. 
  // If the sound is still loudly ringing, we register it as HIGH so it doesn't 
  // re-trigger on the next loop.
  lastMicState = digitalRead(MIC_IN_PIN); 

  // --- 3. HARDWARE-SAFE SLEEP ---
  sleep_enable();
  
  noInterrupts(); // cli() - Pause interrupts temporarily
  
  // Wipe any ghost flags generated by pins dropping LOW while we were awake
  // (Writing a logic 1 to the bit clears it in AVR architecture)
  GIFR = (1 << PCIF); 
  
  interrupts();   // sei() - Unpause interrupts
  sleep_cpu();    // AVR guarantees this executes before any new interrupt can fire
  
  sleep_disable();
}